export interface RoastTemplate {
  id: string;
  category:
    | 'repetition'
    | 'score_low'
    | 'score_high'
    | 'no_veggies'
    | 'protein_addict'
    | 'sauce_lover'
    | 'light_dinner'
    | 'variety'
    | 'general';
  template: string;
  tone: 'roast' | 'kind';
  excludeObjectives?: string[];
}

export const roastTemplates: RoastTemplate[] = [
  // ─── REPETITION (20 roast + 20 kind) ────────────────────
  {
    id: 'rep_01',
    category: 'repetition',
    template: 'Tu as mangé {protein} {count} fois cette semaine. T\'es sponsorisé ou quoi ?',
    tone: 'roast',
  },
  {
    id: 'rep_01k',
    category: 'repetition',
    template: '{protein} {count} fois cette semaine — tu sais ce que tu aimes, c\'est déjà ça !',
    tone: 'kind',
  },
  {
    id: 'rep_02',
    category: 'repetition',
    template: '{protein} encore ? Même Netflix te dirait « t\'as pas déjà vu ça ? »',
    tone: 'roast',
  },
  {
    id: 'rep_02k',
    category: 'repetition',
    template: 'On dirait que {protein} est ton ingrédient fétiche cette semaine. Essaie d\'en découvrir un nouveau la prochaine fois !',
    tone: 'kind',
  },
  {
    id: 'rep_03',
    category: 'repetition',
    template: 'Algorithme de ton frigo : {protein}, {protein}, {protein}, {protein}... et répété.',
    tone: 'roast',
  },
  {
    id: 'rep_03k',
    category: 'repetition',
    template: 'La régularité avec {protein}, c\'est bien. Une petite rotation de plus serait encore mieux !',
    tone: 'kind',
  },
  {
    id: 'rep_04',
    category: 'repetition',
    template: 'Ton assiette a moins de surprises que la fin d\'une série Marvel.',
    tone: 'roast',
  },
  {
    id: 'rep_04k',
    category: 'repetition',
    template: 'Tes repas sont cohérents — ajouter une protéine nouvelle apporterait encore plus de diversité nutritionnelle.',
    tone: 'kind',
  },
  {
    id: 'rep_05',
    category: 'repetition',
    template: 'Si ta semaine était une playlist, ce serait la même chanson en boucle.',
    tone: 'roast',
  },
  {
    id: 'rep_05k',
    category: 'repetition',
    template: 'Une semaine un peu répétitive, mais constante ! La prochaine, on varie un peu ?',
    tone: 'kind',
  },
  {
    id: 'rep_06',
    category: 'repetition',
    template: 'Ton régime alimentaire est en mode copy-paste depuis {count} jours.',
    tone: 'roast',
  },
  {
    id: 'rep_06k',
    category: 'repetition',
    template: 'La constance, c\'est bien ! Tente quand même une nouvelle recette la semaine prochaine.',
    tone: 'kind',
  },
  {
    id: 'rep_07',
    category: 'repetition',
    template: 'Les bactéries de ton intestin commencent à savoir ton menu par cœur.',
    tone: 'roast',
  },
  {
    id: 'rep_07k',
    category: 'repetition',
    template: 'Ton microbiome adore la régularité, mais il apprécierait aussi un peu de nouveauté !',
    tone: 'kind',
  },
  {
    id: 'rep_08',
    category: 'repetition',
    template: '{protein} {count} fois ? T\'as dû racheter le même livre de recettes par erreur.',
    tone: 'roast',
  },
  {
    id: 'rep_08k',
    category: 'repetition',
    template: 'Tu maîtrises {protein} comme un chef. Maintenant, entraîne-toi sur un nouvel ingrédient !',
    tone: 'kind',
  },
  {
    id: 'rep_09',
    category: 'repetition',
    template: 'Ton semainier ressemble au fond d\'un tiroir : toujours la même chose.',
    tone: 'roast',
  },
  {
    id: 'rep_09k',
    category: 'repetition',
    template: 'On voit que tu as tes habitudes. Une petite surprise dans la semaine ça fait du bien !',
    tone: 'kind',
  },
  {
    id: 'rep_10',
    category: 'repetition',
    template: 'Dis-moi que tu n\'as pas le même fond d\'écran depuis 5 ans aussi.',
    tone: 'roast',
  },
  {
    id: 'rep_10k',
    category: 'repetition',
    template: 'La fidélité à {protein}, c\'est admirable ! Pense à varier pour booster ta nutrition.',
    tone: 'kind',
  },
  {
    id: 'rep_11',
    category: 'repetition',
    template: '{protein} {count} fois… même ton estomac regrette de ne pas avoir pris le menu du jour.',
    tone: 'roast',
  },
  {
    id: 'rep_11k',
    category: 'repetition',
    template: 'Un classique en {protein} ! Pense à explorer d\'autres sources de protéines la prochaine fois.',
    tone: 'kind',
  },
  {
    id: 'rep_12',
    category: 'repetition',
    template: 'Ta variété alimentaire, c\'est comme un buffet où on ne sert qu\'un seul plat.',
    tone: 'roast',
  },
  {
    id: 'rep_12k',
    category: 'repetition',
    template: 'Belle fidélité à tes ingrédients préférés ! Un peu plus de diversité, et c\'est parfait.',
    tone: 'kind',
  },
  {
    id: 'rep_13',
    category: 'repetition',
    template: 'Tu prépares {protein} tellement souvent qu\'il commence à te ressembler.',
    tone: 'roast',
  },
  {
    id: 'rep_13k',
    category: 'repetition',
    template: 'Tu es un expert en {protein} maintenant. Prêt(e) à élargir ton répertoire ?',
    tone: 'kind',
  },
  {
    id: 'rep_14',
    category: 'repetition',
    template: 'Ta semaine alimentaire a moins de twists que les plans d\'un Ikea.',
    tone: 'roast',
  },
  {
    id: 'rep_14k',
    category: 'repetition',
    template: 'Une semaine prévisible, c\'est une semaine sans stress. Ajoute juste un ingrédient nouveau !',
    tone: 'kind',
  },
  {
    id: 'rep_15',
    category: 'repetition',
    template: 'Si tes repas étaient un film : « {protein} : l\'épisode {count} ».',
    tone: 'roast',
  },
  {
    id: 'rep_15k',
    category: 'repetition',
    template: 'Tes repas sont cohérents et prévisibles — deux qualités sous-estimées. Juste un soupçon de nouveauté ?',
    tone: 'kind',
  },
  {
    id: 'rep_16',
    category: 'repetition',
    template: 'Même les chefs étoilés font varier leur menu de temps en temps, toi t\'essaies pas trop.',
    tone: 'roast',
  },
  {
    id: 'rep_16k',
    category: 'repetition',
    template: 'Tu as trouvé tes repas de confort — super ! Essaie d\'en ajouter un ou deux nouveaux la semaine prochaine.',
    tone: 'kind',
  },
  {
    id: 'rep_17',
    category: 'repetition',
    template: 'Défi de la semaine : manger quelque chose que tu n\'as pas déjà mangé cette semaine.',
    tone: 'roast',
  },
  {
    id: 'rep_17k',
    category: 'repetition',
    template: 'La routine alimentaire, c\'est rassurant ! Un petit challenge : tester un nouvel ingrédient chaque semaine.',
    tone: 'kind',
  },
  {
    id: 'rep_18',
    category: 'repetition',
    template: 'AssemblEat a généré {count} suggestions différentes pour toi. Tu en as utilisé combien ?',
    tone: 'roast',
  },
  {
    id: 'rep_18k',
    category: 'repetition',
    template: 'Bonne nouvelle : plein de nouvelles suggestions t\'attendent dans l\'app à explorer !',
    tone: 'kind',
  },
  {
    id: 'rep_19',
    category: 'repetition',
    template: 'Ton assiette a un abonnement premium à {protein}. Cancel pour voir ?',
    tone: 'roast',
  },
  {
    id: 'rep_19k',
    category: 'repetition',
    template: '{protein} régulièrement, c\'est une bonne source de protéines ! Varie un peu pour enrichir ta palette.',
    tone: 'kind',
  },
  {
    id: 'rep_20',
    category: 'repetition',
    template: 'T\'as mangé {protein} {count} fois. C\'est de la fidélité ou de l\'oubli ?',
    tone: 'roast',
  },
  {
    id: 'rep_20k',
    category: 'repetition',
    template: 'La consistance avec {protein} montre une vraie discipline. La diversité, c\'est l\'étape suivante !',
    tone: 'kind',
  },

  // ─── SCORE_LOW (15 roast + 15 kind) ────────────────────
  {
    id: 'low_01',
    category: 'score_low',
    template: '3 repas en D cette semaine... même ton frigo est déçu.',
    tone: 'roast',
  },
  {
    id: 'low_01k',
    category: 'score_low',
    template: 'Quelques repas pourraient être améliorés. On va y arriver ensemble !',
    tone: 'kind',
  },
  {
    id: 'low_02',
    category: 'score_low',
    template: 'Nutri-Score D à répétition — même l\'ANSES a arrêté de regarder ton semainier.',
    tone: 'roast',
  },
  {
    id: 'low_02k',
    category: 'score_low',
    template: 'Des améliorations sont possibles sur quelques repas. Pas de panique, chaque jour est une nouvelle chance !',
    tone: 'kind',
  },
  {
    id: 'low_03',
    category: 'score_low',
    template: 'Ton score nutritionnel ressemble à une note d\'exam de fin d\'année raté.',
    tone: 'roast',
  },
  {
    id: 'low_03k',
    category: 'score_low',
    template: 'Tes scores ont de la marge de progression — c\'est motivant non ? On y travaille !',
    tone: 'kind',
  },
  {
    id: 'low_04',
    category: 'score_low',
    template: 'Nutri-Score D encore ? T\'as l\'impression que c\'est une bonne note hein.',
    tone: 'roast',
  },
  {
    id: 'low_04k',
    category: 'score_low',
    template: 'Un ou deux swaps suffiront pour booster tes scores. C\'est plus simple qu\'il n\'y paraît !',
    tone: 'kind',
  },
  {
    id: 'low_05',
    category: 'score_low',
    template: 'Si tes repas avaient des notes scolaires, tu serais en cours de rattrapage.',
    tone: 'roast',
  },
  {
    id: 'low_05k',
    category: 'score_low',
    template: 'Tu pars de loin, mais chaque repas mieux noté est une victoire. Continue !',
    tone: 'kind',
  },
  {
    id: 'low_06',
    category: 'score_low',
    template: 'Ta semaine nutritionnelle a l\'air d\'un code Python écrit un vendredi soir.',
    tone: 'roast',
  },
  {
    id: 'low_06k',
    category: 'score_low',
    template: 'Les scores peuvent s\'améliorer rapidement. Commence par remplacer un ingrédient par semaine.',
    tone: 'kind',
  },
  {
    id: 'low_07',
    category: 'score_low',
    template: '{avgScore} d\'indice d\'équilibre moyen. Même les voisins ont faim pour toi.',
    tone: 'roast',
  },
  {
    id: 'low_07k',
    category: 'score_low',
    template: 'Score moyen de {avgScore} — il y a de la progression possible, et je suis là pour t\'aider !',
    tone: 'kind',
  },
  {
    id: 'low_08',
    category: 'score_low',
    template: 'Ton indice d\'équilibre moyen fait honte aux céréales du rayon petit-déjeuner.',
    tone: 'roast',
  },
  {
    id: 'low_08k',
    category: 'score_low',
    template: 'Des ajustements simples peuvent vraiment faire la différence sur tes scores. Tu gères !',
    tone: 'kind',
  },
  {
    id: 'low_09',
    category: 'score_low',
    template: 'D en Nutri-Score c\'est bien — si t\'essaies de faire le minimum syndical.',
    tone: 'roast',
  },
  {
    id: 'low_09k',
    category: 'score_low',
    template: 'Quelques repas moins bien notés, ça arrive. L\'important c\'est la tendance globale !',
    tone: 'kind',
  },
  {
    id: 'low_10',
    category: 'score_low',
    template: 'Nutri-Score D à la maison — Wolverine mange mieux que toi et il grignote du métal.',
    tone: 'roast',
  },
  {
    id: 'low_10k',
    category: 'score_low',
    template: 'On peut améliorer ça ensemble, step by step. T\'es sur la bonne app pour ça !',
    tone: 'kind',
  },
  {
    id: 'low_11',
    category: 'score_low',
    template: 'Tes repas ont plus de lettres rouges que ton relevé bancaire en fin de mois.',
    tone: 'roast',
  },
  {
    id: 'low_11k',
    category: 'score_low',
    template: 'Chaque amélioration de score, même petite, compte pour ta santé sur le long terme.',
    tone: 'kind',
  },
  {
    id: 'low_12',
    category: 'score_low',
    template: 'Indice d\'équilibre moyen {avgScore} — t\'avais sûrement mieux à faire qu\'étudier les étiquettes.',
    tone: 'roast',
  },
  {
    id: 'low_12k',
    category: 'score_low',
    template: 'Score de {avgScore} cette semaine. L\'app te suggère des alternatives plus nutritives, utilise-les !',
    tone: 'kind',
  },
  {
    id: 'low_13',
    category: 'score_low',
    template: 'Une semaine à D, c\'est comme commander une pizza et mettre « régime » dans sa bio Instagram.',
    tone: 'roast',
  },
  {
    id: 'low_13k',
    category: 'score_low',
    template: 'La semaine n\'a pas été parfaite nutritionnellement, mais tu es là et tu essaies. C\'est ce qui compte.',
    tone: 'kind',
  },
  {
    id: 'low_14',
    category: 'score_low',
    template: 'Tes repas ont visiblement pris un chemin touristique pour arriver à toi.',
    tone: 'roast',
  },
  {
    id: 'low_14k',
    category: 'score_low',
    template: 'Des repas moins optimaux cette semaine — la semaine prochaine, un repas B ou A de plus !',
    tone: 'kind',
  },
  {
    id: 'low_15',
    category: 'score_low',
    template: 'Indice d\'équilibre de la semaine : merci de ne pas partager ta carte d\'identité alimentaire en public.',
    tone: 'roast',
  },
  {
    id: 'low_15k',
    category: 'score_low',
    template: 'Les scores vont s\'améliorer ! Commence par valider plus souvent et l\'app va t\'orienter.',
    tone: 'kind',
  },

  // ─── SCORE_HIGH (15 roast + 15 kind) ────────────────────
  {
    id: 'high_01',
    category: 'score_high',
    template: 'Nutri-Score A 5 jours d\'affilée — t\'as avalé un manuel de nutrition ?',
    tone: 'roast',
  },
  {
    id: 'high_01k',
    category: 'score_high',
    template: 'Nutri-Score A 5 jours d\'affilée — tu es un vrai exemple à suivre !',
    tone: 'kind',
  },
  {
    id: 'high_02',
    category: 'score_high',
    template: 'Tes scores sont si bons qu\'on dirait que tu testes l\'app pour son développeur.',
    tone: 'roast',
  },
  {
    id: 'high_02k',
    category: 'score_high',
    template: 'Des scores excellents cette semaine — ton corps te dit merci !',
    tone: 'kind',
  },
  {
    id: 'high_03',
    category: 'score_high',
    template: 'T\'as un indice d\'équilibre moyen de A. T\'es sûr(e) que tu n\'es pas diététicien(ne) ?',
    tone: 'roast',
  },
  {
    id: 'high_03k',
    category: 'score_high',
    template: 'Score moyen exceptionnel ! Tu as vraiment bien intégré les principes de l\'équilibre alimentaire.',
    tone: 'kind',
  },
  {
    id: 'high_04',
    category: 'score_high',
    template: 'Tes repas sont si équilibrés que même un algorithme serait jaloux.',
    tone: 'roast',
  },
  {
    id: 'high_04k',
    category: 'score_high',
    template: 'Des repas parfaitement équilibrés ! Continue sur cette lancée, tu gères vraiment.',
    tone: 'kind',
  },
  {
    id: 'high_05',
    category: 'score_high',
    template: 'Nutri-Score A toute la semaine ? T\'as une relation trop sérieuse avec tes légumes.',
    tone: 'roast',
  },
  {
    id: 'high_05k',
    category: 'score_high',
    template: 'Semaine nutritionnellement parfaite ! Tu montres que bien manger peut devenir une habitude naturelle.',
    tone: 'kind',
  },
  {
    id: 'high_06',
    category: 'score_high',
    template: 'Tes assiettes ont plus de couleurs que la palette d\'un graphiste sous pression.',
    tone: 'roast',
  },
  {
    id: 'high_06k',
    category: 'score_high',
    template: 'Tes assiettes colorées et équilibrées sont une vraie inspiration. Bravo !',
    tone: 'kind',
  },
  {
    id: 'high_07',
    category: 'score_high',
    template: 'T\'aurais pu financer un labo nutritionnel avec le soin que tu mets dans tes repas.',
    tone: 'roast',
  },
  {
    id: 'high_07k',
    category: 'score_high',
    template: 'L\'attention que tu portes à ta nutrition porte ses fruits. Littéralement.',
    tone: 'kind',
  },
  {
    id: 'high_08',
    category: 'score_high',
    template: 'Tes repas sont si parfaits que même ton diététicien pourrait prendre des notes.',
    tone: 'roast',
  },
  {
    id: 'high_08k',
    category: 'score_high',
    template: 'Semaine exemplaire ! Tu progrès vraiment dans ta façon de composer tes repas.',
    tone: 'kind',
  },
  {
    id: 'high_09',
    category: 'score_high',
    template: 'Nutri-Score A cette semaine. Est-ce qu\'on peut se tutoyer, champion(ne) ?',
    tone: 'roast',
  },
  {
    id: 'high_09k',
    category: 'score_high',
    template: 'Excellente semaine ! Tes choix alimentaires sont vraiment bien optimisés.',
    tone: 'kind',
  },
  {
    id: 'high_10',
    category: 'score_high',
    template: 'T\'as fini premier au classement nutritionnel cette semaine. Premier de quoi ? On ne sait pas. Mais premier.',
    tone: 'roast',
  },
  {
    id: 'high_10k',
    category: 'score_high',
    template: 'On adore voir des semaines comme ça ! Tu es dans le top des utilisateurs AssemblEat.',
    tone: 'kind',
  },
  {
    id: 'high_11',
    category: 'score_high',
    template: 'Si ton assiette était un film : « 2001 : A Food Odyssey ».',
    tone: 'roast',
  },
  {
    id: 'high_11k',
    category: 'score_high',
    template: 'Une semaine qui mérite d\'être encadrée. Tu fais exactement ce qu\'il faut !',
    tone: 'kind',
  },
  {
    id: 'high_12',
    category: 'score_high',
    template: 'Tes repas ont un Nutri-Score si bon que Google voudrait t\'indexer comme source officielle.',
    tone: 'roast',
  },
  {
    id: 'high_12k',
    category: 'score_high',
    template: 'Semaine au top ! Tes choix montrent une vraie compréhension de la nutrition équilibrée.',
    tone: 'kind',
  },
  {
    id: 'high_13',
    category: 'score_high',
    template: 'Nutri-Score A, B, A, B, A — t\'as fait un algorithme ou c\'est instinctif à ce niveau ?',
    tone: 'roast',
  },
  {
    id: 'high_13k',
    category: 'score_high',
    template: 'Une régularité impressionnante dans la qualité nutritionnelle ! Tu as vraiment pris de bonnes habitudes.',
    tone: 'kind',
  },
  {
    id: 'high_14',
    category: 'score_high',
    template: 'T\'es tellement sain(e) que tes légumes te remercient chaque matin.',
    tone: 'roast',
  },
  {
    id: 'high_14k',
    category: 'score_high',
    template: 'Tes légumes et protéines sont parfaitement équilibrés cette semaine. Continue comme ça !',
    tone: 'kind',
  },
  {
    id: 'high_15',
    category: 'score_high',
    template: 'Nutri-Score parfait 3 jours de suite. T\'as pris un abonnement premium à la santé ?',
    tone: 'roast',
  },
  {
    id: 'high_15k',
    category: 'score_high',
    template: '3 jours parfaits d\'affilée — tu construis de vraies habitudes saines. Chapeau !',
    tone: 'kind',
  },

  // ─── NO_VEGGIES (10 roast + 10 kind) ────────────────────
  {
    id: 'veg_01',
    category: 'no_veggies',
    template: 'Tes légumes t\'attendent. Depuis 3 jours. Ils commencent à perdre espoir.',
    tone: 'roast',
  },
  {
    id: 'veg_01k',
    category: 'no_veggies',
    template: 'Les légumes ont été un peu absents cette semaine. Même une portion par jour ferait une grande différence !',
    tone: 'kind',
  },
  {
    id: 'veg_02',
    category: 'no_veggies',
    template: 'Tes micronutriments ont déposé une demande de congés. On leur a dit que t\'acceptais.',
    tone: 'roast',
  },
  {
    id: 'veg_02k',
    category: 'no_veggies',
    template: 'Quelques légumes en plus et tes micronutriments seront au top. Facile à corriger !',
    tone: 'kind',
  },
  {
    id: 'veg_03',
    category: 'no_veggies',
    template: 'Les légumes dans ton assiette : rumeur ou réalité ? L\'enquête continue.',
    tone: 'roast',
  },
  {
    id: 'veg_03k',
    category: 'no_veggies',
    template: 'Ajouter des légumes, même crus ou surgelés, est l\'un des gestes les plus efficaces pour ta santé.',
    tone: 'kind',
  },
  {
    id: 'veg_04',
    category: 'no_veggies',
    template: 'Ton assiette ressemble à une carte postale : plein de couleurs... sauf le vert.',
    tone: 'roast',
  },
  {
    id: 'veg_04k',
    category: 'no_veggies',
    template: 'Il manque juste un peu de verdure dans tes repas cette semaine. Une poignée de légumes suffit !',
    tone: 'kind',
  },
  {
    id: 'veg_05',
    category: 'no_veggies',
    template: 'Les broccolis ont essayé de t\'appeler. Tu n\'as pas décroché.',
    tone: 'roast',
  },
  {
    id: 'veg_05k',
    category: 'no_veggies',
    template: 'Pense aux légumes comme un bonus santé facile à ajouter. Même une salade rapide compte !',
    tone: 'kind',
  },
  {
    id: 'veg_06',
    category: 'no_veggies',
    template: 'Pas de légumes cette semaine ? Bambi est triste.',
    tone: 'roast',
  },
  {
    id: 'veg_06k',
    category: 'no_veggies',
    template: 'Les légumes ont été discrets cette semaine. Intègre-les à tes prochains assemblages, l\'app t\'y aide !',
    tone: 'kind',
  },
  {
    id: 'veg_07',
    category: 'no_veggies',
    template: 'Tes fibres ont fait grève cette semaine. Et elles ont raison.',
    tone: 'roast',
  },
  {
    id: 'veg_07k',
    category: 'no_veggies',
    template: 'Les fibres des légumes font du bien à ta digestion et à ton énergie. Vise une portion par repas !',
    tone: 'kind',
  },
  {
    id: 'veg_08',
    category: 'no_veggies',
    template: 'T\'as un rapport compliqué avec les légumes. Ils, eux, n\'ont pas de rancune.',
    tone: 'roast',
  },
  {
    id: 'veg_08k',
    category: 'no_veggies',
    template: 'Parfois c\'est difficile d\'intégrer des légumes. Commence par celui que tu préfères !',
    tone: 'kind',
  },
  {
    id: 'veg_09',
    category: 'no_veggies',
    template: 'Ton intestin a commandé des légumes. La livraison est en retard de 3 jours.',
    tone: 'roast',
  },
  {
    id: 'veg_09k',
    category: 'no_veggies',
    template: 'Tes légumes sont en attente ! Quelques portions cette semaine feront vraiment la différence.',
    tone: 'kind',
  },
  {
    id: 'veg_10',
    category: 'no_veggies',
    template: 'Zéro légume de la semaine. T\'as la carte Gold chez le primeur sans jamais y aller ?',
    tone: 'roast',
  },
  {
    id: 'veg_10k',
    category: 'no_veggies',
    template: 'Pas de légumes cette semaine — pas grave, la prochaine sera l\'occasion de se rattraper !',
    tone: 'kind',
  },

  // ─── PROTEIN_ADDICT (10 roast + 10 kind) ────────────────────
  {
    id: 'pro_01',
    category: 'protein_addict',
    template: 'Le poulet te connaît par ton prénom maintenant.',
    tone: 'roast',
  },
  {
    id: 'pro_01k',
    category: 'protein_addict',
    template: 'Le poulet est une excellente source de protéines maigres. D\'autres volailles pourraient aussi t\'intéresser !',
    tone: 'kind',
  },
  {
    id: 'pro_02',
    category: 'protein_addict',
    template: 'Tu aimes {protein} comme les boomers aiment les émissions du dimanche soir.',
    tone: 'roast',
  },
  {
    id: 'pro_02k',
    category: 'protein_addict',
    template: '{protein} est une super protéine ! Pour encore plus de bénéfices, varie les sources.',
    tone: 'kind',
  },
  {
    id: 'pro_03',
    category: 'protein_addict',
    template: 'Ton rapport à {protein} commence à ressembler à une relation toxique.',
    tone: 'roast',
  },
  {
    id: 'pro_03k',
    category: 'protein_addict',
    template: '{protein} est là pour toi ! Pense à varier pour diversifier tes apports nutritionnels.',
    tone: 'kind',
  },
  {
    id: 'pro_04',
    category: 'protein_addict',
    template: 'Est-ce que {protein} sait à quel point tu l\'apprécies ? Dis-lui direct.',
    tone: 'roast',
  },
  {
    id: 'pro_04k',
    category: 'protein_addict',
    template: 'Bon choix avec {protein} ! Essaie un nouveau type de protéine la prochaine fois.',
    tone: 'kind',
  },
  {
    id: 'pro_05',
    category: 'protein_addict',
    template: '{protein} {count} fois… même la poule qui le pond est épuisée.',
    tone: 'roast',
  },
  {
    id: 'pro_05k',
    category: 'protein_addict',
    template: '{protein} régulièrement, c\'est une bonne habitude ! Pense à la compléter avec d\'autres protéines.',
    tone: 'kind',
  },
  {
    id: 'pro_06',
    category: 'protein_addict',
    template: '{protein} est jaloux de tes autres ingrédients. Attends — t\'en as pas d\'autres.',
    tone: 'roast',
  },
  {
    id: 'pro_06k',
    category: 'protein_addict',
    template: 'Un seul type de protéine cette semaine. La diversité protéique, c\'est aussi de la diversité nutritionnelle !',
    tone: 'kind',
  },
  {
    id: 'pro_07',
    category: 'protein_addict',
    template: 'Si on faisait une émission culinaire de ta semaine, ça s\'appellerait « {protein} : The Documentary ».',
    tone: 'roast',
  },
  {
    id: 'pro_07k',
    category: 'protein_addict',
    template: '{protein} est clairement ta star de la semaine ! Pour t\'inspirer, explore d\'autres protéines dans l\'app.',
    tone: 'kind',
  },
  {
    id: 'pro_08',
    category: 'protein_addict',
    template: 'T\'as une obsession pour {protein} qui pourrait remplir un livre de psy.',
    tone: 'roast',
  },
  {
    id: 'pro_08k',
    category: 'protein_addict',
    template: 'Tu as clairement trouvé une protéine que tu aimes ! Explore les autres pour plus de nutriments.',
    tone: 'kind',
  },
  {
    id: 'pro_09',
    category: 'protein_addict',
    template: 'Les autres protéines du répertoire regardent ton assiette avec envie et tristesse.',
    tone: 'roast',
  },
  {
    id: 'pro_09k',
    category: 'protein_addict',
    template: 'Tu as ton ingrédient phare. La prochaine étape : explorer le répertoire complet de l\'app !',
    tone: 'kind',
  },
  {
    id: 'pro_10',
    category: 'protein_addict',
    template: 'Résumé de ta semaine protéinée : {protein}, {protein}, {protein}. T\'as un problème ou c\'est assumé ?',
    tone: 'roast',
  },
  {
    id: 'pro_10k',
    category: 'protein_addict',
    template: 'La fidélité à {protein} est cool ! Maintenant, introduis un autre aliment protéiné pour compléter.',
    tone: 'kind',
  },

  // ─── SAUCE_LOVER (5 roast + 5 kind) ────────────────────
  {
    id: 'sau_01',
    category: 'sauce_lover',
    template: 'Sauce soja sur tout ? T\'assaisonnes ou tu noies ?',
    tone: 'roast',
  },
  {
    id: 'sau_01k',
    category: 'sauce_lover',
    template: 'Tu aimes les sauces ! Pense à les choisir avec moins de sel pour optimiser ton équilibre.',
    tone: 'kind',
  },
  {
    id: 'sau_02',
    category: 'sauce_lover',
    template: 'T\'as mis de la sauce sur ta sauce. Respect, mais aussi pourquoi ?',
    tone: 'roast',
  },
  {
    id: 'sau_02k',
    category: 'sauce_lover',
    template: 'Les sauces ajoutent du goût — fais attention au sodium et aux graisses saturées.',
    tone: 'kind',
  },
  {
    id: 'sau_03',
    category: 'sauce_lover',
    template: 'Ta sauce préférée a sa propre carte de fidélité dans ton frigo.',
    tone: 'roast',
  },
  {
    id: 'sau_03k',
    category: 'sauce_lover',
    template: 'Bonne idée de varier les sauces ! Certaines maison sont aussi délicieuses et bien meilleures pour toi.',
    tone: 'kind',
  },
  {
    id: 'sau_04',
    category: 'sauce_lover',
    template: 'Les ingrédients sont là pour habiller ta sauce, c\'est ça ?',
    tone: 'roast',
  },
  {
    id: 'sau_04k',
    category: 'sauce_lover',
    template: 'Tu aimes les saveurs prononcées, c\'est super ! Explore des épices pour moins de sauce mais plus de goût.',
    tone: 'kind',
  },
  {
    id: 'sau_05',
    category: 'sauce_lover',
    template: 'On t\'a inscrit dans le club « Mon assiette est un océan de sauce ». Bienvenue.',
    tone: 'roast',
  },
  {
    id: 'sau_05k',
    category: 'sauce_lover',
    template: 'Tu sais cuisiner avec des sauces — pense à équilibrer pour ne pas masquer les saveurs naturelles.',
    tone: 'kind',
  },

  // ─── LIGHT_DINNER (5 roast + 5 kind) ────────────────────
  {
    id: 'lig_01',
    category: 'light_dinner',
    template: 'Dîner léger 4 fois ? Ton estomac te remercie à 2h du mat\'.',
    tone: 'roast',
  },
  {
    id: 'lig_01k',
    category: 'light_dinner',
    template: '4 dîners légers cette semaine — excellent pour la récupération et le sommeil !',
    tone: 'kind',
  },
  {
    id: 'lig_02',
    category: 'light_dinner',
    template: 'T\'as dîné si léger cette semaine que t\'as failli t\'envoler.',
    tone: 'roast',
  },
  {
    id: 'lig_02k',
    category: 'light_dinner',
    template: 'Des dîners légers réguliers, c\'est l\'une des meilleures habitudes pour ton métabolisme !',
    tone: 'kind',
  },
  {
    id: 'lig_03',
    category: 'light_dinner',
    template: 'Ton dîner léger récurrent — c\'est de la santé ou juste la flemme de cuisiner ?',
    tone: 'roast',
  },
  {
    id: 'lig_03k',
    category: 'light_dinner',
    template: 'Les dîners légers sont vraiment bénéfiques. Continue sur cette lancée, c\'est une super habitude !',
    tone: 'kind',
  },
  {
    id: 'lig_04',
    category: 'light_dinner',
    template: 'Dîner léger à répétition. T\'as un abonnement à la sagesse diététique ou c\'est un accident ?',
    tone: 'roast',
  },
  {
    id: 'lig_04k',
    category: 'light_dinner',
    template: 'Tu maîtrises vraiment l\'art du dîner léger ! Ton corps et ton sommeil t\'en sont reconnaissants.',
    tone: 'kind',
  },
  {
    id: 'lig_05',
    category: 'light_dinner',
    template: 'Légèreté au dîner {count} fois — soit t\'es diété, soit t\'as oublié de faire les courses.',
    tone: 'roast',
  },
  {
    id: 'lig_05k',
    category: 'light_dinner',
    template: '{count} dîners légers — une habitude santé que beaucoup rêvent d\'avoir. Bravo !',
    tone: 'kind',
  },

  // ─── VARIETY (5 roast + 5 kind) ────────────────────
  {
    id: 'var_01',
    category: 'variety',
    template: '12 ingrédients différents cette semaine. T\'es un vrai chef ou juste indécis ?',
    tone: 'roast',
  },
  {
    id: 'var_01k',
    category: 'variety',
    template: '{uniqueIngredients} ingrédients différents cette semaine — c\'est une semaine nutritionnellement riche !',
    tone: 'kind',
  },
  {
    id: 'var_02',
    category: 'variety',
    template: 'Autant de variété dans ton assiette que dans une playlist aléatoire. C\'est un compliment ?',
    tone: 'roast',
  },
  {
    id: 'var_02k',
    category: 'variety',
    template: 'Belle diversité alimentaire cette semaine ! La variété, c\'est vraiment la clé d\'une nutrition optimale.',
    tone: 'kind',
  },
  {
    id: 'var_03',
    category: 'variety',
    template: '{uniqueIngredients} ingrédients différents. T\'as un doctorat en instabilité culinaire ?',
    tone: 'roast',
  },
  {
    id: 'var_03k',
    category: 'variety',
    template: 'Impressionnant ! {uniqueIngredients} ingrédients différents — ton microbiome est aux anges.',
    tone: 'kind',
  },
  {
    id: 'var_04',
    category: 'variety',
    template: 'Ta semaine alimentaire, c\'est le festival Coachella de la nutrition. Trop ?',
    tone: 'roast',
  },
  {
    id: 'var_04k',
    category: 'variety',
    template: 'Une variété remarquable cette semaine ! Tu nourris ton corps avec une belle palette de nutriments.',
    tone: 'kind',
  },
  {
    id: 'var_05',
    category: 'variety',
    template: 'Autant d\'ingrédients différents, c\'est soit du génie, soit t\'arrives jamais à finir tes courses.',
    tone: 'roast',
  },
  {
    id: 'var_05k',
    category: 'variety',
    template: 'Excellente variété ! Maintenir cette diversité sur la durée, c\'est l\'objectif ultime.',
    tone: 'kind',
  },

  // ─── GENERAL (10 roast + 10 kind) ────────────────────
  {
    id: 'gen_01',
    category: 'general',
    template: 'Bilan de ta semaine alimentaire : intéressant. Très… intéressant.',
    tone: 'roast',
  },
  {
    id: 'gen_01k',
    category: 'general',
    template: 'Une semaine avec des hauts et des bas — c\'est normal ! L\'important c\'est la tendance globale.',
    tone: 'kind',
  },
  {
    id: 'gen_02',
    category: 'general',
    template: 'Ton semainier ressemble à une œuvre d\'art moderne : personne ne comprend vraiment.',
    tone: 'roast',
  },
  {
    id: 'gen_02k',
    category: 'general',
    template: 'Ta semaine alimentaire a sa propre personnalité ! Continuons à l\'affiner ensemble.',
    tone: 'kind',
  },
  {
    id: 'gen_03',
    category: 'general',
    template: '{totalMeals} repas validés cette semaine. La médaille d\'assiduité est… en transit.',
    tone: 'roast',
  },
  {
    id: 'gen_03k',
    category: 'general',
    template: '{totalMeals} repas validés — chaque repas tracé est un pas vers de meilleures habitudes !',
    tone: 'kind',
  },
  {
    id: 'gen_04',
    category: 'general',
    template: 'Si on faisait un documentaire sur tes repas, le titre serait « L\'ordinaire du quotidien ».',
    tone: 'roast',
  },
  {
    id: 'gen_04k',
    category: 'general',
    template: 'Une semaine régulière, c\'est une bonne semaine. Chaque repas compte !',
    tone: 'kind',
  },
  {
    id: 'gen_05',
    category: 'general',
    template: 'Analyse de ta semaine : tu as mangé. C\'est déjà ça. Vraiment.',
    tone: 'roast',
  },
  {
    id: 'gen_05k',
    category: 'general',
    template: 'Tu utilises l\'app, tu suis tes repas — c\'est déjà une vraie démarche positive !',
    tone: 'kind',
  },
  {
    id: 'gen_06',
    category: 'general',
    template: 'T\'as {totalMeals} repas sur les {possible} possibles. Le verre est à moitié vide, ou plein de {protein} ?',
    tone: 'roast',
  },
  {
    id: 'gen_06k',
    category: 'general',
    template: '{totalMeals} repas tracés — bonne continuité ! Plus tu valides, plus l\'app t\'aide à t\'améliorer.',
    tone: 'kind',
  },
  {
    id: 'gen_07',
    category: 'general',
    template: 'Ton alimentation cette semaine : entre le génie et l\'improvisation totale.',
    tone: 'roast',
  },
  {
    id: 'gen_07k',
    category: 'general',
    template: 'Une semaine avec des moments inspirés ! Continuons à construire là-dessus.',
    tone: 'kind',
  },
  {
    id: 'gen_08',
    category: 'general',
    template: 'T\'as validé {totalMeals} repas. AssemblEat te donne une mention « encourageante ».',
    tone: 'roast',
  },
  {
    id: 'gen_08k',
    category: 'general',
    template: '{totalMeals} repas validés — chaque validation aide l\'app à mieux te connaître !',
    tone: 'kind',
  },
  {
    id: 'gen_09',
    category: 'general',
    template: 'Si ta semaine était un mème, ce serait « expectation vs reality ».',
    tone: 'roast',
  },
  {
    id: 'gen_09k',
    category: 'general',
    template: 'La semaine a eu ses défis alimentaires. La prochaine sera meilleure — on y va ensemble !',
    tone: 'kind',
  },
  {
    id: 'gen_10',
    category: 'general',
    template: 'Résumé nutritionnel : quelque chose entre « pourrait mieux faire » et « fait mieux ».',
    tone: 'roast',
  },
  {
    id: 'gen_10k',
    category: 'general',
    template: 'Tu suis tes repas, tu utilises l\'app — tu es déjà sur la bonne voie vers de meilleures habitudes !',
    tone: 'kind',
  },
];
